# Generated by Django 5.1.6 on 2025-02-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_dispositivo_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
