# Generated by Django 5.1.6 on 2025-02-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_dispositivo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
    ]
