# Generated by Django 5.1.7 on 2025-03-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
