# Generated by Django 5.1.7 on 2025-03-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techfinder', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sistema_operativo',
            field=models.CharField(blank=True, choices=[('Windows', 'Windows'), ('MacOS', 'MacOS'), ('Linux', 'Linux'), ('Android', 'Android'), ('iOS', 'iOS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Laptop', 'Laptops'), ('Computador Torre', 'Computadores Torre'), ('Smartphone', 'Smartphones'), ('Smartwatch', 'Relojes Inteligentes'), ('Tablet', 'Tablets')], max_length=100),
        ),
    ]
