# Generated by Django 5.1.7 on 2025-03-15 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techfinder', '0003_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
